### ISSUE TITLE
[Android] screenSize appears to be wrong on the hardware

### ISSUE THREAD

**Issue by andrioid** [mybigday/react-native-external-display#259]
I'm using Android on hardware from a producer called PAX and they device has a secondary screen on the back that I want to use.

The `screenSize` reports width: 533.33, height: 853.33 and using `flex: 1` also matches that. However, that only covers 1/3 (interestingly almost exactly 3 times) of the screen width. I'd be happy to contribute if you could tell me where the sizes are calculated.

I noticed that if I override the View width/height inside the ExternalDisplay, I can easily render whatever I want (even larger than the display thinks it is).

I would like to fix it so that `flex` works and to get the screenSize to match the actual display.

Edit: My theory is that dpi is interfering [here](https://github.com/mybigday/react-native-external-display/blob/master/packages/react-native-external-display/android/src/main/java/com/externaldisplay/ExternalDisplayHelper.java#L49) and according to [DisplayMetrics docs](https://developer.android.com/reference/android/util/DisplayMetrics#widthPixels) the size is in absolutePixels and might need to be adjusted for [React Native sizes](https://reactnative.dev/docs/height-and-width) or density-independent-pixels.

Edit 2: The Android `display.getRealScreensize()` returns the correct resolution, but the `scale` part in the JS code seems to mess it up. Can anyone explain why iOS gets scale=1 and Android gets whatever the main screen has?

![img_1006](https://user-images.githubusercontent.com/271599/109982154-e8da6c00-7d01-11eb-9921-fb0aae0b50e5.jpg)

**Comment by jhen0409** [comment]
> The Android display.getRealScreensize() returns the correct resolution, but the scale part in the JS code seems to mess it up. Can anyone explain why iOS gets scale=1 and Android gets whatever the main screen has?

This is because the View layout calculation is followed main display, so if we use the real size, you can see our test results in simulate display of Android Emulator:

### [Unexpected] Use real size

![Screen Shot 2021-05-14 at 3 52 22 PM](https://user-images.githubusercontent.com/3001525/118239498-712c7880-b4cc-11eb-9314-fc088b009230.png)

### [Expected] Use real size / main display scale

![Screen Shot 2021-05-14 at 3 52 08 PM](https://user-images.githubusercontent.com/3001525/118239653-a2a54400-b4cc-11eb-9bad-22233ea3fc19.png)

I don't know what the main cause of this issue is. I don't have a real Android tablet at the moment. So if there is any solution, PR is always welcome.

**Comment by rorkyendo** [comment]
i had the same issue here..
The second screen just in half screen

![WhatsApp Image 2022-02-12 at 10 16 45](https://user-images.githubusercontent.com/38852429/153694736-1cea3808-88a7-44c0-a8ab-d70cc0273f84.jpeg)

**Comment by jhen0409** [comment]
It may be fixed by #413. Thanks @rorkyendo!

Released as v0.5.15.
